### ISSUE TITLE
Need your help on scripted dashboard

### ISSUE THREAD

**Issue by Amaradana** [eostermueller/applesToApples#3]
Hi,  I did not have an alternate communication to reach you. So posting here appologies for it.

I am trying to build a dashboard with multiple templates and data sources. Currently if template fields are more page grafana page looks clumsy. 

my dashboard looks like below

template 1 template 2 template 3 template 4 template 5 template 6 template 7 template 8 template 9 template 10 template 11 etc

table panel 1 (loads data based on template 1 template 2 they are all from same data source 1)
table pane 2 (loads data based on template 3 template 4 they are all from same data source 2)
table panel 3 (loads data based on template 5 template 6 they are all from same data source 3)
table panel 4 (loads data based on template 7 template 8 they are all from same data source 4)
table panel 5 (loads data based on template 9 template 10 they are all from same data source 5)
etc

each table panel will have multiple values where they load dynamicallly selecting 2 template values for each table

is there a way where i can create a dashboard as below through scripted dashboard

template 1 template 2

table panel 1

template 4 template 3

table panel 2

template 5 template 6

table panel 3

**Comment by Amaradana** [comment]
If this is possible can you send me a snippet code. I can't use docker as I will not have privileges to install as my laptop is doesn't support docker

**Comment by eostermueller** [comment]
No I don’t know how to do it, but I see where you’re headed — a good idea.

Perhaps abandon the scripted dashboard and try using a “panel” plugin? Or
perhaps an “app” plugin?

https://grafana.com/plugins?type=panel


Good luck, let me know if you find a solution.
—Erik

**Comment by Amaradana** [comment]
Not possible with Panels, need a custom panel like others where we can drag and drop. right now i only see scripted dashboard as alternate but will let you know if i was able to succed. other easy solution is create multiple dashboards with different panels and hyperlink them in single dashboard but i think thats my least option, i wish there is a panel from drop down in Grafana which is easy

**Comment by eostermueller** [comment]
You can also create a table, where each row is a link to a scripted dashboard:

label1 http://grafana_url/dashboard/script/scripted.js?myDataSource1
label2 http://grafana_url/dashboard/script/scripted.js?myDataSource2
label3 http://grafana_url/dashboard/script/scripted.js?myDataSource3



or you can create the above links in a text panel using markdown.
https://grafana.com/plugins/text

**Comment by Amaradana** [comment]
Thank you, am still working on it, I Apologies for delay in reply. i had added some more custom fields as per the requirements, can you please tell me how you build the jar, i mean command used to build the jar.

I used gradlew build to  get the jar but its not working when i was testing with jmeter and below is the error

018-10-05 13:07:46,683 ERROR o.a.j.JMeter: Uncaught exception: 
java.lang.NoClassDefFoundError: org/influxdb/InfluxDBFactory
	at rocks.nt.apm.jmeter.JMeterInfluxDBBackendListenerClient.setupInfluxClient(JMeterInfluxDBBackendListenerClient.java:261) ~[JMeter-InfluxDB-Writer-v-1.2x-1.0x.jar:1.0x]
	at rocks.nt.apm.jmeter.JMeterInfluxDBBackendListenerClient.setupTest(JMeterInfluxDBBackendListenerClient.java:190) ~[JMeter-InfluxDB-Writer-v-1.2x-1.0x.jar:1.0x]
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:337) ~[ApacheJMeter_components.jar:4.0 r1823414]
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:292) ~[ApacheJMeter_components.jar:4.0 r1823414]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:215) ~[ApacheJMeter_core.jar:4.0 r1823414]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:384) ~[ApacheJMeter_core.jar:4.0 r1823414]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]

**Comment by eostermueller** [comment]
Maven should work, else make sure your gradle configuration has org/influxdb/InfluxDBFactory as a dependency.
